apiVersion: v1
kind: Service
metadata:
  name: realtime-balance-service
spec:
  selector:
    app: realtime-balance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
  type: LoadBalancer  # LoadBalancer 可用于对外暴露服务